// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  case_studies: dynamic(() => import("./CaseStudies")),
  case_studies_carousel: dynamic(() => import("./CaseStudiesCarousel")),
  hero: dynamic(() => import("./Hero")),
  masonry_cards: dynamic(() => import("./MasonryCards")),
  process: dynamic(() => import("./Process")),
  rich_text: dynamic(() => import("./RichText")),
  services: dynamic(() => import("./Services")),
  single_review: dynamic(() => import("./SingleReview")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
